// Edit this file to add or change portraits. Each entry:
//   { name, photo (in portraits/), song (path to audio) }
// Then just open index.html — no server needed.
window.GALLERY_DATA = {
  items: [
    {"name": "Banban", "photo": "banban.jpg", "song": "musique_portrait/54-46 Was My Number.mp3"},
    {"name": "Felix", "photo": "felix.jpg", "song": "musique_portrait/Nasty Girl (feat. Diddy, Nelly, Jagged Edge & Avery Storm) - 2005 Remaster.mp3"},
    {"name": "Guillaume", "photo": "guillaume.jpg", "song": "musique_portrait/Tunak Tunak Tun.mp3"},
    {"name": "Ghis", "photo": "ghis.jpg", "song": "musique_portrait/Black Hole Sun.mp3"},
    {"name": "Oleg", "photo": "Oleg.jpg", "song": "musique_portrait/Rain.mp3"},
    {"name": "Nourrdin", "photo": "Nourrdin.jpg", "song": "musique_portrait/Fadma.mp3"},
    {"name": "Chakib", "photo": "Chakib.jpg", "song": "musique_portrait/Az Khod Gozashteh.mp3"},
    {"name": "Tarek", "photo": "Tarek.jpg", "song": "musique_portrait/Dima Maghreb.mp3"},
    {"name": "Larbii", "photo": "Larbii.jpg", "song": "musique_portrait/Calm Down.mp3"},
    {"name": "Huang Wenxi", "photo": "Huang Wenxi.jpg", "song": "musique_portrait/過完冬季.mp3"},
    {"name": "Amine", "photo": "Amine.jpg", "song": "musique_portrait/Tarab Andaluci.mp3"},
    {"name": "Miriam", "photo": "Miriam.jpg", "song": "musique_portrait/505.mp3"},
    {"name": "Mohammed Bus", "photo": "Mohammed bus.jpg", "song": "musique_portrait/Inas Inas.mp3"},
    {"name": "Mohammed Coooop", "photo": "Mohammed coooop.jpg", "song": "musique_portrait/Mazal souvenir andi.mp3"},
    {"name": "Fifi", "photo": "fifi.jpg", "song": "musique_portrait/Ballade pour Adeline (Piano et orchestre).mp3"},
    {"name": "Ismail", "photo": "ismail.jpg", "song": "musique_portrait/Seret El Hob.mp3"},
    {"name": "Fif", "photo": "fif.jpg", "song": "musique_portrait/Strange Planet.mp3"},
    {"name": "Abdeljelil", "photo": "abdeljelil.jpg", "song": "musique_portrait/Europa (Earth's Cry Heaven's Smile).mp3"},
    {"name": "Mehjoub", "photo": "mehjoub.jpg", "song": "musique_portrait/La Illaha Illa Allah.mp3"},
    {"name": "Konan", "photo": "konan.jpg", "song": "musique_portrait/Canopee.mp3"},
    {"name": "Stijn", "photo": "stijn.jpg", "song": "musique_portrait/Kwaku the Traveller.mp3"},
    {"name": "Benzee", "photo": "Benzee.jpg", "song": "musique_portrait/Jungle.mp3"},
    {"name": "James", "photo": "James.jpg", "song": "musique_portrait/Feeling Good.mp3"},
    {"name": "David", "photo": "David.jpg", "song": "musique_portrait/Rafiki - Original Mix.mp3"},
    {"name": "Tancrède", "photo": "Tancrède.jpg", "song": "musique_portrait/The Great Gig In The Sky - 2023 Remaster.mp3"},
    {"name": "Vincent", "photo": "Vincent.jpg", "song": "musique_portrait/Bohemian Rhapsody Queen.mp3"},
    {"name": "Abdou", "photo": "abdou.jpg", "song": "musique_portrait/Jbali Mohammed Rouicha.mp3"},
    {"name": "Ahmed", "photo": "ahmed.jpg", "song": "musique_portrait/homemade_djembe.m4a"},
    {"name": "Said", "photo": "Said.jpg", "song": "musique_portrait/Three Little Birds Bob Marley The Wailers.mp3"},
    {"name": "Mehdi", "photo": "Mehdi.jpg", "song": "musique_portrait/Is This Love Bob Marley The Wailers.mp3"},
    {"name": "Axel", "photo": "axel.jpg", "song": "musique_portrait/GTB.mp3"},
    {"name": "Marin", "photo": "marin.jpg", "song": "musique_portrait/QQTR.mp3"},
  ],
};
